### PR TITLE
Update Ruby version constraints to allow Ruby v2.6

### PR DESCRIPTION
**Pull request by FinnWoelm**
Hi there,

Great gem! I just updated to Ruby v2.6, but acts_as_hashids is unhappy with my update. I pulled this repo and ran all tests locally with Ruby v2.6 and everything appears fine.

Thoughts? :grin:

### CODE REVIEW

**Comment by FinnWoelm** [comment]
Not sure why code coverage decreased :sob:

**Comment by FinnWoelm** [comment]
Hey @dtaniwaki — just following up on this. Any chance of merge? :slightly_smiling_face:

**Comment by FinnWoelm** [comment]
@dtaniwaki — any update on this? Would love to keep using this official repository rather than creating/maintaining my own fork of it.

**Review by dtaniwaki — APPROVED** [review]
LGTM! Thank you for your contribution.

**Pull request merged**
